version: '3'

services:
  pg-mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
    volumes:
      - ./server:/app/server:ro
      # Conditional volume mounts - won't fail if directory doesn't exist
      - ${PWD}/extension_context:/app/extension_context:ro
    command: python -m server.app
    restart: unless-stopped

  # Optional: Add a PostgreSQL database for testing
  # postgres:
  #   image: postgres:15
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_DB=testdb
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

# volumes:
#   postgres_data:
